2024-07-10 23:18:11,996 INFO: 192.168.112.1 - - [10/Jul/2024 23:18:11] "[33mDELETE /dietas/23 HTTP/1.1[0m" 404 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:18:14,667 INFO: 192.168.112.1 - - [10/Jul/2024 23:18:14] "[33mDELETE /dietas/24 HTTP/1.1[0m" 404 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:18:16,951 INFO: Dieta com ID 25 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:18:16,952 INFO: 192.168.112.1 - - [10/Jul/2024 23:18:16] "DELETE /dietas/25 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:18:20,148 INFO: 192.168.112.1 - - [10/Jul/2024 23:18:20] "[31m[1mPOST /dietas/25 HTTP/1.1[0m" 405 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:20:13,768 INFO: 192.168.112.1 - - [10/Jul/2024 23:20:13] "[31m[1mPOST /dietas/25 HTTP/1.1[0m" 405 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:20:15,153 INFO: 192.168.112.1 - - [10/Jul/2024 23:20:15] "[31m[1mPOST /dietas/25 HTTP/1.1[0m" 405 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:21:17,866 INFO: Dieta criada com sucesso: {'id': 28, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []} [in /app/app.py:39]
2024-07-10 23:21:17,867 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:21:17,868 INFO: 192.168.112.1 - - [10/Jul/2024 23:21:17] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:21:28,659 INFO: Listagem de dietas realizada: [{'id': 28, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:21:28,660 INFO: 192.168.112.1 - - [10/Jul/2024 23:21:28] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:24:48,045 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:24:48,106 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.128.3:5001 [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:24:48,107 INFO: [33mPress CTRL+C to quit[0m [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:25:01,624 INFO: Dieta com ID 28 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:25:01,625 INFO: 192.168.128.1 - - [10/Jul/2024 23:25:01] "DELETE /dietas/28 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:25:05,715 INFO: Listagem de dietas realizada: [] [in /app/app.py:78]
2024-07-10 23:25:05,717 INFO: 192.168.128.1 - - [10/Jul/2024 23:25:05] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:25:19,734 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:25:19,735 INFO: 192.168.128.1 - - [10/Jul/2024 23:25:19] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:25:25,502 INFO: Listagem de dietas realizada: [{'id': 29, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:25:25,503 INFO: 192.168.128.1 - - [10/Jul/2024 23:25:25] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:27:09,822 INFO: Dieta com ID 29 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:27:09,823 INFO: 192.168.128.1 - - [10/Jul/2024 23:27:09] "DELETE /dietas/29 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:27:23,008 INFO: 192.168.128.1 - - [10/Jul/2024 23:27:23] "[31m[1mPOST /dietas/29 HTTP/1.1[0m" 405 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:27:31,866 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:27:31,869 INFO: 192.168.128.1 - - [10/Jul/2024 23:27:31] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:27:36,270 INFO: Listagem de dietas realizada: [{'id': 30, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:27:36,271 INFO: 192.168.128.1 - - [10/Jul/2024 23:27:36] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:22,012 INFO: Listagem de dietas realizada: [{'id': 30, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:29:22,015 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:22] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:26,237 ERROR: Erro de integridade ao criar dieta: (pymysql.err.IntegrityError) (1062, "Duplicate entry 'abc123xyz' for key 'dietas.firebase_uuid'")
[SQL: INSERT INTO dietas (firebase_uuid) VALUES (%(firebase_uuid)s)]
[parameters: {'firebase_uuid': 'abc123xyz'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /app/app.py:65]
2024-07-10 23:29:26,239 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:26] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:30,990 INFO: Listagem de dietas realizada: [{'id': 30, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:29:30,992 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:30] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:36,471 INFO: Dieta com ID 30 deletada com sucesso. [in /app/app.py:94]
2024-07-10 23:29:36,472 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:36] "DELETE /dietas/30 HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:40,115 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:29:40,117 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:40] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:46,346 INFO: Listagem de dietas realizada: [{'id': 32, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:29:46,347 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:46] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:54,851 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:54] "OPTIONS /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:29:54,862 ERROR: Erro desconhecido ao criar dieta: 'DietaCreate' object has no attribute 'horarios_refeicoes' [in /app/app.py:69]
2024-07-10 23:29:54,864 INFO: 192.168.128.1 - - [10/Jul/2024 23:29:54] "[35m[1mPOST /dietas HTTP/1.1[0m" 500 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:30:02,377 INFO: Listagem de dietas realizada: [{'id': 32, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}, {'id': 33, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:30:02,379 INFO: 192.168.128.1 - - [10/Jul/2024 23:30:02] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:36:10,959 INFO: Listagem de dietas realizada: [{'id': 32, 'firebase_uuid': 'abc123xyz', 'horarios_refeicoes': [], 'refeicoes': []}, {'id': 33, 'firebase_uuid': 'V5nmLXsJlJRC5lvs53TxOnFPvPv1', 'horarios_refeicoes': [], 'refeicoes': []}] [in /app/app.py:78]
2024-07-10 23:36:10,961 INFO: 192.168.128.1 - - [10/Jul/2024 23:36:10] "GET /dietas HTTP/1.1" 200 - [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:37:11,337 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:38:51,547 INFO: Logging setup complete [in /app/logs/log_config.py:25]
2024-07-10 23:38:51,618 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.160.3:5001 [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
2024-07-10 23:38:51,620 INFO: [33mPress CTRL+C to quit[0m [in /usr/local/lib/python3.10/site-packages/werkzeug/_internal.py:187]
